### ISSUE TITLE
Why is `Tweet::text` truncated sometimes?

### ISSUE THREAD

**Issue by vityafx** [dmizuk/twitter-stream-rs#10]
I have just reposted a tweet and it's text is:

    text: "RT @QuakeRussia: Quake Champions BETA countdown April 27: The next QC Beta will start at 16:00 CEST (10:00AM EST) Read More https://t.co/OT…",

However in the same structure if we try to see `entities::retweeted_status` it's text is:

    text: "Quake Champions BETA countdown April 27: The next QC Beta will start at 16:00 CEST (10:00AM EST) Read More https://t.co/OTcq6H6sXU",

The full object looks like this:

[bug.txt](https://github.com/dmizuk/twitter-stream-rs/files/964216/bug.txt)

**Comment by dmizuk** [comment]
That's a normal behavior in Twitter's spec. Twitter truncates `text` field of a retweet if the text (including `RT @user_name: `) would exceed 140 characters. See the [doc for `Tweet.truncated` field](https://docs.rs/twitter-stream/0.3/twitter_stream/tweet/struct.Tweet.html#truncated.v).

So, in case of a retweet, it's recommended to refer to `text` field of `Tweet.retweeted_status`, instead of `Tweet.text`.

Maybe I should write additional docs for this pitfall later.

**Comment by vityafx** [comment]
@dmizuk Nice, thanks much for the explanation.
